//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfhealthapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public AdminUser()
        {
            this.HospitalsMasters = new HashSet<HospitalsMaster>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string AccessIP { get; set; }
        public string Name { get; set; }
    
        public virtual RoleMaster RoleMaster { get; set; }
        public virtual ICollection<HospitalsMaster> HospitalsMasters { get; set; }
    }
}
