//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfhealthapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string TimeFrom { get; set; }
        public string TimeTo { get; set; }
        public string AppointmentReason { get; set; }
        public Nullable<bool> IsApprovedByDoc { get; set; }
        public Nullable<bool> IsCancelledByPat { get; set; }
        public Nullable<bool> IsMeetingHeld { get; set; }
        public Nullable<System.DateTime> AppointmentCreatedOn { get; set; }
        public string DoctorRemarks { get; set; }
        public string PatientRemarks { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> PatientId { get; set; }
    
        public virtual UsersMaster UsersMaster { get; set; }
        public virtual UsersMaster UsersMaster1 { get; set; }
    }
}
