//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfhealthapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<int> Doctor_Id { get; set; }
        public string FeedbackBy { get; set; }
        public Nullable<System.DateTime> FeedbackGivenOn { get; set; }
        public Nullable<System.DateTime> FeedbackApprovedOn { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> Rating { get; set; }
        public string CommentsGiven { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Hospital_Id { get; set; }
    
        public virtual HospitalsMaster HospitalsMaster { get; set; }
        public virtual UsersMaster UsersMaster { get; set; }
        public virtual UsersMaster UsersMaster1 { get; set; }
    }
}
