//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfhealthapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public Nullable<int> PatiendId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string Feedback1 { get; set; }
        public Nullable<System.DateTime> FeedbackGivenOn { get; set; }
        public Nullable<bool> IsApprovedByDoctor { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual UsersMaster UsersMaster { get; set; }
        public virtual UsersMaster UsersMaster1 { get; set; }
    }
}
