//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfhealthapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalsMaster
    {
        public HospitalsMaster()
        {
            this.UsersInHospitals = new HashSet<UsersInHospital>();
        }
    
        public int Id { get; set; }
        public string HospName { get; set; }
        public string Address { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string Lati { get; set; }
        public string Longi { get; set; }
        public string Description { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
        public virtual ICollection<UsersInHospital> UsersInHospitals { get; set; }
    }
}
