//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfhealthapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalsMaster
    {
        public HospitalsMaster()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Feedbacks = new HashSet<Feedback>();
            this.PrescriptionAttachments = new HashSet<PrescriptionAttachment>();
            this.Prescriptions = new HashSet<Prescription>();
            this.ReferralsSentByDoctors = new HashSet<ReferralsSentByDoctor>();
            this.ReferralsSentByPatients = new HashSet<ReferralsSentByPatient>();
            this.UsersInHospitals = new HashSet<UsersInHospital>();
        }
    
        public int Id { get; set; }
        public string HospName { get; set; }
        public string Address { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy_Super_Admin { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string Lati { get; set; }
        public string Longi { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual SuperAdminUser SuperAdminUser { get; set; }
        public virtual ICollection<PrescriptionAttachment> PrescriptionAttachments { get; set; }
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        public virtual ICollection<ReferralsSentByDoctor> ReferralsSentByDoctors { get; set; }
        public virtual ICollection<ReferralsSentByPatient> ReferralsSentByPatients { get; set; }
        public virtual ICollection<UsersInHospital> UsersInHospitals { get; set; }
    }
}
