//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfhealthapi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wfhealthdbEntities : DbContext
    {
        public wfhealthdbEntities()
            : base("name=wfhealthdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<HospitalsMaster> HospitalsMasters { get; set; }
        public virtual DbSet<ReferralsSentByPatient> ReferralsSentByPatients { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<UsersInHospital> UsersInHospitals { get; set; }
        public virtual DbSet<UsersMaster> UsersMasters { get; set; }
    }
}
