//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfhealthapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionAttachment
    {
        public int Id { get; set; }
        public string DocPath { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Appointment_Id { get; set; }
        public Nullable<int> Doctor_Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<int> Hospital_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Docsummary { get; set; }
        public Nullable<int> Prescription_Id { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual HospitalsMaster HospitalsMaster { get; set; }
        public virtual Prescription Prescription { get; set; }
        public virtual UsersMaster UsersMaster { get; set; }
        public virtual UsersMaster UsersMaster1 { get; set; }
    }
}
