//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfhealthapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMaster
    {
        public RoleMaster()
        {
            this.SuperAdminUsers = new HashSet<SuperAdminUser>();
            this.UsersMasters = new HashSet<UsersMaster>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string RoleDescription { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ICollection<SuperAdminUser> SuperAdminUsers { get; set; }
        public virtual ICollection<UsersMaster> UsersMasters { get; set; }
    }
}
