//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfhealthapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDetail
    {
        public int Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Website { get; set; }
        public string Speciality { get; set; }
        public string Description { get; set; }
        public string skypeId { get; set; }
    
        public virtual UsersMaster UsersMaster { get; set; }
    }
}
