//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfhealthapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersMaster
    {
        public UsersMaster()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Appointments1 = new HashSet<Appointment>();
            this.DoctorTimings = new HashSet<DoctorTiming>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Feedbacks1 = new HashSet<Feedback>();
            this.PrescriptionAttachments = new HashSet<PrescriptionAttachment>();
            this.PrescriptionAttachments1 = new HashSet<PrescriptionAttachment>();
            this.Prescriptions = new HashSet<Prescription>();
            this.Prescriptions1 = new HashSet<Prescription>();
            this.ReferralsSentByDoctors = new HashSet<ReferralsSentByDoctor>();
            this.ReferralsSentByDoctors1 = new HashSet<ReferralsSentByDoctor>();
            this.ReferralsSentByDoctors2 = new HashSet<ReferralsSentByDoctor>();
            this.ReferralsSentByPatients = new HashSet<ReferralsSentByPatient>();
            this.ReferralsSentByPatients1 = new HashSet<ReferralsSentByPatient>();
            this.UsersInHospitals = new HashSet<UsersInHospital>();
            this.UsersMaster1 = new HashSet<UsersMaster>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string ContactNum { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public string DeviceType { get; set; }
        public string NotificationToken { get; set; }
        public string Lati { get; set; }
        public string Longi { get; set; }
        public string eMail { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Created_By { get; set; }
        public string ImagePath { get; set; }
        public string DOB { get; set; }
        public string AccessToken { get; set; }
        public Nullable<System.DateTime> LastSeenOn { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Appointment> Appointments1 { get; set; }
        public virtual ICollection<DoctorTiming> DoctorTimings { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Feedback> Feedbacks1 { get; set; }
        public virtual ICollection<PrescriptionAttachment> PrescriptionAttachments { get; set; }
        public virtual ICollection<PrescriptionAttachment> PrescriptionAttachments1 { get; set; }
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        public virtual ICollection<Prescription> Prescriptions1 { get; set; }
        public virtual ICollection<ReferralsSentByDoctor> ReferralsSentByDoctors { get; set; }
        public virtual ICollection<ReferralsSentByDoctor> ReferralsSentByDoctors1 { get; set; }
        public virtual ICollection<ReferralsSentByDoctor> ReferralsSentByDoctors2 { get; set; }
        public virtual ICollection<ReferralsSentByPatient> ReferralsSentByPatients { get; set; }
        public virtual ICollection<ReferralsSentByPatient> ReferralsSentByPatients1 { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
        public virtual ICollection<UsersInHospital> UsersInHospitals { get; set; }
        public virtual ICollection<UsersMaster> UsersMaster1 { get; set; }
        public virtual UsersMaster UsersMaster2 { get; set; }
    }
}
